from pytest import mark

from ansiscape import InterpretationDict, interpret
from ansiscape.enums import BlinkSpeed, Intensity, Underline, VerticalPosition


@mark.parametrize(
    "code, expect",
    [
        (
            "",
            InterpretationDict(
                blink_speed=None,
                intensity=None,
                italic=None,
                underline=None,
                vertical_position=None,
            ),
        ),
        (
            "-1",
            InterpretationDict(
                blink_speed=None,
                intensity=None,
                italic=None,
                underline=None,
                vertical_position=None,
            ),
        ),
        (
            "-1;73",
            InterpretationDict(
                blink_speed=None,
                intensity=None,
                italic=None,
                underline=None,
                vertical_position=None,
            ),
        ),
        (
            "0",
            InterpretationDict(
                blink_speed=BlinkSpeed.NONE,
                intensity=Intensity.NORMAL,
                italic=False,
                underline=Underline.NONE,
                vertical_position=VerticalPosition.NONE,
            ),
        ),
        (
            "1",
            InterpretationDict(
                blink_speed=None,
                intensity=Intensity.BOLD,
                italic=None,
                underline=None,
                vertical_position=None,
            ),
        ),
        (
            "2",
            InterpretationDict(
                blink_speed=None,
                intensity=Intensity.DIM,
                italic=None,
                underline=None,
                vertical_position=None,
            ),
        ),
        (
            "3",
            InterpretationDict(
                blink_speed=None,
                intensity=None,
                italic=True,
                underline=None,
                vertical_position=None,
            ),
        ),
        (
            "4",
            InterpretationDict(
                blink_speed=None,
                intensity=None,
                italic=None,
                underline=Underline.SINGLE,
                vertical_position=None,
            ),
        ),
        (
            "5",
            InterpretationDict(
                blink_speed=BlinkSpeed.SLOW,
                intensity=None,
                italic=None,
                underline=None,
                vertical_position=None,
            ),
        ),
        (
            "6",
            InterpretationDict(
                blink_speed=BlinkSpeed.FAST,
                intensity=None,
                italic=None,
                underline=None,
                vertical_position=None,
            ),
        ),
        (
            "21",
            InterpretationDict(
                blink_speed=None,
                intensity=None,
                italic=None,
                underline=Underline.DOUBLE,
                vertical_position=None,
            ),
        ),
        (
            "23",
            InterpretationDict(
                blink_speed=None,
                intensity=None,
                italic=False,
                underline=None,
                vertical_position=None,
            ),
        ),
        (
            "24",
            InterpretationDict(
                blink_speed=None,
                intensity=None,
                italic=None,
                underline=Underline.NONE,
                vertical_position=None,
            ),
        ),
        (
            "25",
            InterpretationDict(
                blink_speed=BlinkSpeed.NONE,
                intensity=None,
                italic=None,
                underline=None,
                vertical_position=None,
            ),
        ),
        (
            "73",
            InterpretationDict(
                blink_speed=None,
                intensity=None,
                italic=None,
                underline=None,
                vertical_position=VerticalPosition.SUPERSCRIPT,
            ),
        ),
        (
            "74",
            InterpretationDict(
                blink_speed=None,
                intensity=None,
                italic=None,
                underline=None,
                vertical_position=VerticalPosition.SUBSCRIPT,
            ),
        ),
        (
            "75",
            InterpretationDict(
                blink_speed=None,
                intensity=None,
                italic=None,
                underline=None,
                vertical_position=VerticalPosition.NONE,
            ),
        ),
        (
            "73;1",
            InterpretationDict(
                blink_speed=None,
                intensity=Intensity.BOLD,
                italic=None,
                underline=None,
                vertical_position=VerticalPosition.SUPERSCRIPT,
            ),
        ),
        (
            "0;73",
            InterpretationDict(
                blink_speed=BlinkSpeed.NONE,
                intensity=Intensity.NORMAL,
                italic=False,
                underline=Underline.NONE,
                vertical_position=VerticalPosition.SUPERSCRIPT,
            ),
        ),
        (
            "73;74",
            InterpretationDict(
                blink_speed=None,
                intensity=None,
                italic=None,
                underline=None,
                vertical_position=VerticalPosition.SUBSCRIPT,
            ),
        ),
    ],
)
def test_interpret(code: str, expect: InterpretationDict) -> None:
    assert interpret(code) == expect
